apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: matrix
  name: matrix-clientsa
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: client-auth
  namespace: matrix
spec:
  method: kubernetes
  mount: matrix
  kubernetes:
    role: matrix-client
    serviceAccount: matrix-clientsa
    audiences:
      - vault