apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: matrix
  name: matrix-mongodbsa
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: mongodb-auth
  namespace: matrix
spec:
  method: kubernetes
  mount: matrix
  kubernetes:
    role: matrix-mongodb
    serviceAccount: matrix-mongodbsa
    audiences:
      - vault