apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: matrix
  name: matrix-serversa
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: server-auth
  namespace: matrix
spec:
  method: kubernetes
  mount: matrix
  kubernetes:
    role: matrix-server
    serviceAccount: matrix-serversa
    audiences:
      - vault