apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-kv-client
  namespace: matrix
spec:
  type: kv-v2

  # mount path
  mount: matrix

  # path of the secret
  path: client

  # dest k8s secret
  destination:
    name: clientkv
    create: true

  # static secret refresh interval
  refreshAfter: 30s

  # Name of the CRD to authenticate to Vault
  vaultAuthRef: client-auth