apiVersion: v1
kind: Service
metadata:
  name: "mongo-service"
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "matrix.labels-mongo" . | nindent 4 }}
spec:
  type: {{ .Values.mongo.service.type }}
  ports:
    - port: {{ .Values.mongo.service.port }}
      targetPort: {{ .Values.mongo.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "matrix.selectorLabels-mongo" . | nindent 4 }}
