apiVersion: v1
kind: Service
metadata:
  name: "server-service"
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "matrix.labels-server" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: {{ .Values.server.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "matrix.selectorLabels-server" . | nindent 4 }}
